# Generated by Django 6.1.1 on 2026-09-05 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RecursoEducativo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_archivo", models.CharField(max_length=500)),
                ("ruta_completa", models.CharField(max_length=1000, unique=True)),
                ("extension", models.CharField(blank=True, max_length=20, null=True)),
                ("categoria", models.CharField(db_index=True, max_length=100)),
                (
                    "tipo_contenido",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("tamanio_bytes", models.IntegerField()),
                ("fecha_creacion", models.DateTimeField()),
                ("fecha_modificacion", models.DateTimeField()),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("etiquetas", models.TextField(blank=True, null=True)),
                ("importado_el", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["categoria", "nombre_archivo"],
                "indexes": [
                    models.Index(
                        fields=["categoria"], name="core_recurs_categor_c1ff19_idx"
                    ),
                    models.Index(
                        fields=["nombre_archivo"], name="core_recurs_nombre__231adb_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Curso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("descripcion", models.TextField()),
                ("categoria", models.CharField(db_index=True, max_length=100)),
                (
                    "nivel",
                    models.CharField(
                        choices=[
                            ("PRIMARIA", "Primaria"),
                            ("SECUNDARIA", "Secundaria"),
                            ("BACHILLERATO", "Bachillerato"),
                            ("UNIVERSITARIO", "Universitario"),
                            ("POSGRADO", "Posgrado"),
                            ("LIBRE", "Libre"),
                        ],
                        default="LIBRE",
                        max_length=20,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador"),
                            ("PUBLICADO", "Publicado"),
                            ("ARCHIVADO", "Archivado"),
                        ],
                        default="BORRADOR",
                        max_length=20,
                    ),
                ),
                ("duracion_horas", models.IntegerField(default=10)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                ("imagen_url", models.URLField(blank=True, null=True)),
                ("palabras_clave", models.CharField(blank=True, max_length=500)),
                (
                    "precio",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "recursos",
                    models.ManyToManyField(
                        blank=True, related_name="cursos", to="core.recursoeducativo"
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_creacion"],
                "indexes": [
                    models.Index(
                        fields=["categoria"], name="core_curso_categor_baa930_idx"
                    ),
                    models.Index(fields=["nivel"], name="core_curso_nivel_799b03_idx"),
                    models.Index(
                        fields=["estado"], name="core_curso_estado_3887ff_idx"
                    ),
                ],
            },
        ),
    ]
