# Generated by Django 6.1.1 on 2026-09-06 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("language_practice", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Evaluacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("EXAMEN", "Examen"),
                            ("PRACTICA", "Práctica"),
                            ("PROYECTO", "Proyecto"),
                            ("FINAL", "Final"),
                        ],
                        default="EXAMEN",
                        max_length=20,
                    ),
                ),
                ("preguntas", models.JSONField(blank=True, default=list)),
                ("puntaje_maximo", models.IntegerField(default=100)),
                ("duracion_minutos", models.IntegerField(default=30)),
                ("nota_minima", models.IntegerField(default=60)),
                ("fecha_publicacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_limite", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluaciones",
                        to="core.curso",
                    ),
                ),
                (
                    "leccion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluaciones",
                        to="language_practice.lesson",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_publicacion"],
            },
        ),
        migrations.CreateModel(
            name="Practica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("EJERCICIO", "Ejercicio"),
                            ("QUIZ", "Quiz"),
                            ("DIAGNOSTICO", "Diagnóstico"),
                            ("REPASO", "Repaso"),
                        ],
                        default="EJERCICIO",
                        max_length=20,
                    ),
                ),
                ("preguntas", models.JSONField(blank=True, default=list)),
                ("puntaje_maximo", models.IntegerField(default=100)),
                ("duracion_minutos", models.IntegerField(default=15)),
                ("orden", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="practicas",
                        to="core.curso",
                    ),
                ),
                (
                    "leccion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="practicas",
                        to="language_practice.lesson",
                    ),
                ),
            ],
            options={
                "ordering": ["orden", "fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="EjercicioInteractivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("OPCION_MULTIPLE", "Opción Múltiple"),
                            ("VERDADERO_FALSO", "Verdadero/Falso"),
                            ("COMPLETAR", "Completar"),
                            ("ORDENAR", "Ordenar"),
                            ("RELACIONAR", "Relacionar"),
                            ("TEXTO", "Texto Libre"),
                        ],
                        default="OPCION_MULTIPLE",
                        max_length=20,
                    ),
                ),
                ("pregunta", models.TextField()),
                ("opciones", models.JSONField(blank=True, default=list)),
                ("respuesta_correcta", models.TextField()),
                ("explicacion", models.TextField(blank=True, null=True)),
                ("puntaje", models.IntegerField(default=5)),
                ("orden", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "evaluacion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ejercicios",
                        to="core.evaluacion",
                    ),
                ),
                (
                    "practica",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ejercicios",
                        to="core.practica",
                    ),
                ),
            ],
            options={
                "ordering": ["orden"],
            },
        ),
    ]
